fix free function oneapi::this_work_item::get_work_group<1>(); for oneapi version > 2024.1
root cause was the following error message:
[ 50%] Building CXX object src/clue_alpaka/CMakeFiles/mainAlpaka.dir/__/main.cpp.o
In file included from /home/**/workspace/clue/src/main.cpp:14:
In file included from /home/**/workspace/clue/clueLib/include/CLUEAlgoAlpaka.h:3:
In file included from /home/**/workspace/clue/alpaka/include/alpaka/alpaka.hpp:13:
In file included from /home/**/workspace/clue/alpaka/include/alpaka/api/oneApi.hpp:10:
In file included from /home/**/workspace/clue/alpaka/include/alpaka/api/oneApi/Queue.hpp:11:
/home/**/workspace/clue/alpaka/include/alpaka/api/oneApi/StaticSharedMemory.hpp:71:53: error: no member named 'this_work_item' in namespace 'sycl::ext::oneapi'
   71 |                     auto group = sycl::ext::oneapi::this_work_item::get_work_group<1>();
      |                                  ~~~~~~~~~~~~~~~~~~~^
/home/s7393169/workspace/clue/alpaka/include/alpaka/api/oneApi/StaticSharedMemory.hpp:71:91: error: expected expression
   71 |                     auto group = sycl::ext::oneapi::this_work_item::get_work_group<1>();
      |                                                                                           ^
2 errors generated.
gmake[2]: *** [src/clue_alpaka/CMakeFiles/mainAlpaka.dir/build.make:76: src/clue_alpaka/CMakeFiles/mainAlpaka.dir/__/main.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:175: src/clue_alpaka/CMakeFiles/mainAlpaka.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2

class StaticSharedMemory now get passed the sycl::nd_item<Dim> const& item which retrieves the group -> auto group = item.get_group(); in the alloc function
the sycl::nd_item<Dim> const& item is now a const reference member of the StaticSharedMemory class.
Therefore StaticSharedMemory and its subclass now have a constexpr Dim variable in its signature.

moved struct MetaData out of the function scope so that sizeLookupBufferInBytes() can be called without the need to specifiy a Dim constexpr variable for the signature.